# Dynamic Programming Made Easy
#### Youn-Long Lin
Department of Computer Science
National Tsing Hua University
Hsinchu, TAIWAN
ylin@cs.nthu.edu.tw

This notebook gives Python implementations of four classical dynamic programming problems. Each problem is in turn implemented in three different approaches:
1. Straight forward (intuitive) recursive coding following the solution formulation
2. Dictionary-based memorization scheme
3. Iteratively looping over solution arrays

The first approach is easy to understand, but it usually leads to exponential run time. The second strategy reduces the run time significantly, but it is subject to OS constraint on the depth of recursive calls. It nevertheless provides insights on solving ordering of subproblems. The third program is built based observing the behavior of the second one.

There are many resources available for learning dynamic programming. Usually they present only one approach (the third one). Most students have difficulty comprehending the logic behind just a few lines of code. By introducing the evolving steps, we hope students will appreciate the beauty of DP.
Problems covered are:
1. Fibonacci Sequence Generation
2. Longest Common Subsequence of Two Strings
3. Text Justification for Word Processing
4. Minimizing Number of Multiplications of Chain of Matrices

We don't provide complete definition of the problems. Students may want to consult their text books for detail problem formulation. Each problem requires different type of arrays and different access patterns. Students are encouraged to try on each one with their own data.

## 1 Fibonacci Sequence

### 1.1 Fibonacci Sequence -- Brute Force Approach
This approach is intuitive. We just follow the definition. Unfortunately, it runs in exponential time due to redundant calls.

In [13]:
def fib_bf(n):
    '''Brute Force Approach'''
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib_bf(n-1) + fib_bf(n-2)
    
fib_bf(10)

55

### 1.2 Fibinacci Sequence -- Dictionary Approach

We use a dictionary to store found solutions to subproblem. The program looks up the dictionary first. If an entry exists in the dictionary, it returns the solution; Otherwise, it calculates the solution, and stores it into the dictionary before returning it to the caller. We print out the insertion sequence to the dictionary.

In [14]:
def fib_dict(n):
    '''Dictionary-based Approach'''
    sol_dict = {0:0, 1:1}
    return fib_dict_engine(n, sol_dict)

def fib_dict_engine(n, sol_dict):
    if n in sol_dict:
        return sol_dict[n]
    else:
        sol = fib_dict_engine(n-1, sol_dict) + fib_dict_engine(n-2, sol_dict)
        sol_dict[n] = sol
        print ('Fib Insert Entry {0} with Value {1}'.format(n, sol))
        return sol

fib_dict(10)

Fib Insert Entry 2 with Value 1
Fib Insert Entry 3 with Value 2
Fib Insert Entry 4 with Value 3
Fib Insert Entry 5 with Value 5
Fib Insert Entry 6 with Value 8
Fib Insert Entry 7 with Value 13
Fib Insert Entry 8 with Value 21
Fib Insert Entry 9 with Value 34
Fib Insert Entry 10 with Value 55


55

### 1.3 Fibonacci Sequence -- Iterative Appraoch
By obeserving what happen to the dictionary above, we know that a 1D array is needed and a simple loop over it will find our solutions.

In [15]:
def fib_loop(n):
    '''DP and List'''
    sol = [-1 for i in range(n+1)]
    sol[0] = 0
    sol[1] = 1
    for i in range(2, n+1):
        sol[i] = sol[i-1] + sol[i-2]
    print ('Fibonacci Sequence of length {} ='.format(n), sol)
    return sol[-1]

fib_loop(10)

Fibonacci Sequence of length 10 = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


55

## 2 Longest Common Subsequence (LCS)

LCS takes two charater strings and find out the longest subsequence common to them both. For example, strings 'Kitten' and 'Knitting' have a length 5 LCS in 'Kittn'.

### 2.1 Longest Common Subsequence -- Brute Force Approach
An intuitive solution is to compare the last characters of the two strings. If they are identical, we know the length is one plus the LCS length of the remaining one-character-shorter strings; otherwise, the solution should be the maximum of two cases, each with one shorter string.

In [16]:
def lcs_bf(x, y):
    '''Brute Force'''
    if len(x) == 0 or len(y) == 0:
        return 0
    else:
        if x[-1] == y[-1]:
            return lcs_bf(x[:-1], y[:-1]) + 1
        else:
            return max(lcs_bf(x[:-1], y), lcs_bf(x, y[:-1]))
        
lcs_bf('Kitten', 'Knitting')
        

5

### 2.2 Longest Common Subsequence -- Dictionary-Based Approach
We use a dictionary with input string lengths as key.

In [17]:
def lcs_dict(x, y):
    sol_dict = {}
    return lcs_dict_engine(x, y, sol_dict)

def lcs_dict_engine(x, y, sol_dict):
    key = str(len(x))+'+'+str(len(y))
    if key in sol_dict:
        return sol_dict[key]
    else:
        if len(x) == 0 or len(y) == 0:
            sol = 0
        else:
            if x[-1] == y[-1]:
                sol = lcs_dict_engine(x[:-1], y[:-1], sol_dict) + 1    
            else:
                sol = max(lcs_dict_engine(x[:-1], y, sol_dict),
                          lcs_dict_engine(x, y[:-1], sol_dict))
        sol_dict[key] = sol
        print ("LCS Insert Dict entry {} with value {}".format(key, sol))
        return sol

lcs_dict('Kitten', 'Knitting')

LCS Insert Dict entry 0+8 with value 0
LCS Insert Dict entry 0+7 with value 0
LCS Insert Dict entry 0+6 with value 0
LCS Insert Dict entry 0+5 with value 0
LCS Insert Dict entry 0+4 with value 0
LCS Insert Dict entry 0+3 with value 0
LCS Insert Dict entry 0+2 with value 0
LCS Insert Dict entry 0+0 with value 0
LCS Insert Dict entry 1+1 with value 1
LCS Insert Dict entry 1+2 with value 1
LCS Insert Dict entry 1+3 with value 1
LCS Insert Dict entry 1+4 with value 1
LCS Insert Dict entry 1+5 with value 1
LCS Insert Dict entry 1+6 with value 1
LCS Insert Dict entry 1+7 with value 1
LCS Insert Dict entry 1+8 with value 1
LCS Insert Dict entry 2+6 with value 2
LCS Insert Dict entry 2+7 with value 2
LCS Insert Dict entry 2+8 with value 2
LCS Insert Dict entry 2+3 with value 2
LCS Insert Dict entry 2+4 with value 2
LCS Insert Dict entry 3+5 with value 3
LCS Insert Dict entry 3+6 with value 3
LCS Insert Dict entry 3+7 with value 3
LCS Insert Dict entry 3+8 with value 3
LCS Insert Dict entry 3+4

5

### 2.3 Longest Common Subsequence -- Iterative Approach
Observing the dictionary above in action, we employ a two dimensional array and fill it up row by row and column by column.

In [18]:
import numpy as np

def lcs_loop(x, y):
    dp_array = np.zeros((len(x)+1, len(y)+1), dtype = int)
    for r in  range (1, len(x) + 1):
        for c in range(1, len(y) + 1):
            if (x[r-1] == y[c-1]):
                dp_array[r, c] = dp_array[r-1, c-1] + 1
            else:
                dp_array[r, c] = max(dp_array[r, c-1], dp_array[r-1, c])
    print (dp_array)
    return dp_array[r, c]

lcs_loop('Kitten', 'Knitting')

[[0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2]
 [0 1 1 2 3 3 3 3 3]
 [0 1 1 2 3 4 4 4 4]
 [0 1 1 2 3 4 4 4 4]
 [0 1 2 2 3 4 4 5 5]]


5

## 3 Text Justification
This problem is also called type setting. It breaks a paragraph of words into lines such that the formatting is pleasant to read. Word processor such as LaTex employs it for high-quality layout.

### 3.1 Text Justification -- Brute Force Approach
The cost is defined as the cost of the first line plus the recursive cost of the remainder of the paragraph. There are multiple options of packing into the first line as long as it doesn't use up the page width. We choose the minimum cost one.

In [19]:
def text_just_bf(text_list, start, end, width):
    '''Brute Force Approach'''
    if start == end:
        return 0
    min_cost = 99999999
    candidate = start
    usage = -1
    while (candidate < end and usage + 1 + len(text_list[candidate]) <= width):
        usage = usage + 1 + len(text_list[candidate])
        line_cost = (width - usage)**2
        curr_cost = line_cost + text_just_bf(text_list, candidate+1, end, width)
        if curr_cost < min_cost:
            min_cost = curr_cost
        candidate += 1
    return min_cost
        
    

text = 'It was the best of time. It was the worst of time.'.split()
text_just_bf(text, 0, len(text), 30)

61

### 3.2 Text Justification --- Dictionary Based Approach
We employ a dictionary to store found solutions to subproblems and obseve the sequence of entry insertion.

In [20]:
def text_just_dict(text_list, start, end, width):
    sol_dict = {}
    return tj_engine(text_list, start, end, width, sol_dict)

def tj_engine(text_list, start, end, width, sol_dict):
    '''Recursive Engine for Dictionary-Based Text Justification'''  
    key = str(start)+'--'+str(end)
    if key in sol_dict:
        return sol_dict[key]
    else:
        if start == end:
            min_cost = 0
        else:
            min_cost = 9999999
            candidate = start
            usage = -1
            while (candidate < end and usage + 1 + len(text_list[candidate]) <= width):
                usage = usage + 1 + len(text_list[candidate])
                line_cost = (width - usage)**2
                curr_cost = line_cost + tj_engine(text_list, candidate+1, end, width, sol_dict)
                if curr_cost < min_cost:
                    min_cost = curr_cost
                candidate += 1

        sol_dict[key] = min_cost
        print ("TJ Insert key {} with value {}".format(key, min_cost))
        return sol_dict[key]
        
    

text = 'It was the best of time. It was the worst of time.'.split()
text_just_dict(text, 0, len(text), 30)

TJ Insert key 12--12 with value 0
TJ Insert key 11--12 with value 625
TJ Insert key 10--12 with value 484
TJ Insert key 9--12 with value 256
TJ Insert key 8--12 with value 144
TJ Insert key 7--12 with value 64
TJ Insert key 6--12 with value 25
TJ Insert key 5--12 with value 452
TJ Insert key 4--12 with value 369
TJ Insert key 3--12 with value 244
TJ Insert key 2--12 with value 164
TJ Insert key 1--12 with value 100
TJ Insert key 0--12 with value 61


61

### 3.3 Text Justification --- Iterative Approach
Observing the dictionary in action above, we find that we need a 1D array to fill up backward. When filling up an entry, we need to look back a variable number of filled entries. Therefore, a while loop is employeed.

In [21]:
import numpy as np

def text_just_loop(text_list, width):
    N = len(text_list)
    dp_array = [999999] * (N+1)
    dp_array[N] = 0
    for n in range(N-1, -1, -1):
        candidate = n
        usage = -1
        min_cost = 9999999
        while (candidate < N and usage + 1 + len(text_list[candidate]) <= width):
            usage = usage + 1 + len(text_list[candidate])
            line_cost = (width - usage)**2
            curr_cost = line_cost + dp_array[candidate+1]
            if curr_cost < min_cost:
                min_cost = curr_cost
            candidate += 1
        dp_array[n] = min_cost
    print (dp_array)
    return dp_array[0]
        
    

text = 'It was the best of time. It was the worst of time.'.split()
text_just_loop(text, 30)

[61, 100, 164, 244, 369, 452, 25, 64, 144, 256, 484, 625, 0]


61

## 4 Chain Matrix Multiplication
To multiply three matrices, A, B and C, we can do it as (A*B)*C or A*(B*C). The number of multiplication operations could be drastically different. This problem asks for a best ordering that minimizes the number of multiplication operations.

### 4.1 Chain Matrix Multiplication -- Brute Force Approach
An intuitive approach is to compare the cost of every multiplication as the last one. So the cost is the recursive cost of the left part plus that of the right part plus the last multiplication. Again we choose the minimum one among all possibilities.

In [22]:
def chain_mat_bf(x):
    if len(x) <= 1:
        return 0
    return min([chain_mat_bf(x[:i+1]) + chain_mat_bf(x[i+1:]) + x[0][0] * x[i][1] * x[-1][1] 
                for i in range(0, len(x)-1)])


y = [(2, 5), (5, 100), (100, 3), (3, 9)]
chain_mat_bf(y)

1584

### 4.2 Chain Matrix Multiplication -- Dictionary Based Approach
We employ a dictionary to record found subproblem solutions.

In [23]:
def chain_mat_dict(x):
    sol_dict = {}
    return chain_mat_dict_engine(x, 0, len(x)-1, sol_dict)

def chain_mat_dict_engine(x, start, end, sol_dict):
    key = str(start)+'+'+str(end)
    if key in sol_dict:
        return sol_dict[key]
    else:
        if start == end:
            sol_dict[key] = 0
        else:
            sol_dict[key] = min([chain_mat_dict_engine(x, i+1, end, sol_dict) +
                                 chain_mat_dict_engine(x, start, i, sol_dict) +
                                 x[start][0] * x[i][1] * x[end][1] 
                                 for i in range(start, end)])
        print ("Insert Key {} with Value {}".format(key, sol_dict[key]))
        return sol_dict[key]
    
y = [(2, 5), (5, 100), (100, 3), (3, 9)]
chain_mat_dict(y)

Insert Key 3+3 with Value 0
Insert Key 2+2 with Value 0
Insert Key 2+3 with Value 2700
Insert Key 1+1 with Value 0
Insert Key 1+2 with Value 1500
Insert Key 1+3 with Value 1635
Insert Key 0+0 with Value 0
Insert Key 0+1 with Value 1000
Insert Key 0+2 with Value 1530
Insert Key 0+3 with Value 1584


1584

### 4.3 Chain Matrix Multiplication --- Iterative Approach
Observing above dictionary in action, we realize that we need a 2D array. We only need to fill up its upper triangle from bottom-right.

In [24]:
def chain_mat_loop(x):
    N = len(x)
    dp_array = np.zeros((N, N), dtype = int)
    if N <= 1:
        return 0
    for r in  range(N-1, -1, -1):
        dp_array[r, r] = 0
        for c in  range(r+1, N):
            dp_array[r,c] = min([dp_array[r, i] + dp_array[i+1, c] + x[r][0]*x[i][1]*x[c][1]
                                 for i in range(r, c)])
    print (dp_array)
    return dp_array[r,c]

y = [(2, 5), (5, 100), (100, 3), (3, 9)]
chain_mat_loop(y)

[[   0 1000 1530 1584]
 [   0    0 1500 1635]
 [   0    0    0 2700]
 [   0    0    0    0]]


1584

## 5. Summary

We have shown Python implementations of four classical dynamic programming problems. We presented three different approaches for each problem. The Dictionary-based approach helps us understanding the ordering of subproblems solved. Therefore, implementation of the iterative approach become easy.

There are many more dynamic programming problems. Students are encouraged to solve them using design patterns learned here.