### Simplex Method for Linear Programming
#### Youn-Long Lin, Department of Computer Science, National Tsing Hua University, TAIWAN

In [62]:
import numpy as np

np.set_printoptions(precision = 2, suppress = True)

# Maximizing an objective function subject to inequalities constraints
def simplex(tableau_in, swapcol_in):
    tableau = np.copy(tableau_in)
    swapcol = np.copy(swapcol_in)
    (num_row, num_col) = tableau.shape
    num_ineq = num_row - 1                  # Number of inequalities
    num_slack = num_ineq                    # Number of slack variables
    num_var = num_col - num_slack - 1 - 1   # Number of variables
    print ("\nInitial Tableau\n", tableau)
    print ("Initial Swap Column\n", swapcol)
    # While last row has negative entries
    while (tableau[-1, np.argmin(tableau[-1, :])] < 0):
        # Designate pivot column the column with most negative entry in the last row
        pivotcol = np.argmin(tableau[-1,:])
        # Designate pivot row the row with smallest ratio between RHS and pivot column
        pivotrow = np.argmin(tableau[0:num_ineq, -1] / tableau[0:num_ineq, pivotcol])
        # Normalize pivot row such that its pivot column element becomes 1
        tableau[pivotrow, :] = tableau[pivotrow, :] / tableau[pivotrow, pivotcol]
        # Normalize non-pivot rows such that its pivot column element becomes 0
        for m in range(num_row):
            if m != pivotrow:
                tableau[m, :] = tableau[m, :] - tableau[pivotrow, :] * tableau[m, pivotcol]
        # Update Swap Column According to Pivot Column
        swapcol[pivotrow] = pivotcol
        print ("\nTableau in progress\n", tableau)
        print ("Swap Col in progressing\n", swapcol)
        
    # Derive variable setting
    var_setting = np.zeros(num_var)
    for i in range(num_ineq):
        if swapcol[i] in range(num_var):
            var_setting[swapcol[i]] = tableau[i, -1]
    return var_setting, tableau, swapcol
    
    

In [66]:
'''
We want to
   Maximize p = 7.0 * x0 + 8.0 * x1 + 10.0 * x2
   subject to
       2.0 * x0 + 3.0 * x1 + 1.0 * x2 <= 1000.0
       1.0 * x0 + 1.0 * x1 + 2.0 * x2 <= 800.0
   in addition to
       x0, x1, x2 >= 0
       
The Tableau denotes
       2.0 * x0 + 3.0 * x1 + 1.0 * x2 + 1.0 * s0 + 0.0 * s1 + 0.0 * p = 1000.0
       1.0 * x0 + 1.0 * x1 + 2.0 * x2 + 0.0 * s0 + 1.0 * s1 + 0.0 * p = 800.0
      -7.0 * x0 - 8.0 * x1 - 10.0 * x2 + 0.0 * s0 + 0.0 * s1 + 1.0 * p = 0.0
'''

tableau_to_solve = np.array([[2.0, 3.0, 2.0, 1.0, 0.0, 0.0, 1000.0],
                             [1.0, 1.0, 2.0, 0.0, 1.0, 0.0, 800.0],
                             [-7.0, -8.0, -10.0, 0.0, 0.0, 1.0, 0.0]])
swapcol_to_solve = np.array([3, 4, 5])      # initialize to [s0, s1, p]

print ("Tableau to Solve\n", tableau_to_solve)
print ("Swap Col to Solve\n", swapcol_to_solve)

var_setting, tableau_out, swapcol_out = simplex(tableau_to_solve, swapcol_to_solve)
p_list = [var_setting[j] * (-1) * tableau_to_solve[-1, j] for j in range(len(var_setting))]
p = sum(p_list)

print ("\nTableau Result\n", tableau_out)
print ("Swap Col Result\n", swapcol_out)
print ("Variable Setting\n", var_setting)
print ("Object Function Value\n", p_list, "sum to", p)
print ("Tableau[-1, -1] =", tableau_out[-1, -1])

Tableau to Solve
 [[    2.     3.     2.     1.     0.     0.  1000.]
 [    1.     1.     2.     0.     1.     0.   800.]
 [   -7.    -8.   -10.     0.     0.     1.     0.]]
Swap Col to Solve
 [3 4 5]

Initial Tableau
 [[    2.     3.     2.     1.     0.     0.  1000.]
 [    1.     1.     2.     0.     1.     0.   800.]
 [   -7.    -8.   -10.     0.     0.     1.     0.]]
Initial Swap Column
 [3 4 5]

Tableau in progress
 [[    1.      2.      0.      1.     -1.      0.    200. ]
 [    0.5     0.5     1.      0.      0.5     0.    400. ]
 [   -2.     -3.      0.      0.      5.      1.   4000. ]]
Swap Col in progressing
 [3 2 5]

Tableau in progress
 [[    0.5      1.       0.       0.5     -0.5      0.     100.  ]
 [    0.25     0.       1.      -0.25     0.75     0.     350.  ]
 [   -0.5      0.       0.       1.5      3.5      1.    4300.  ]]
Swap Col in progressing
 [1 2 5]

Tableau in progress
 [[    1.      2.      0.      1.     -1.      0.    200. ]
 [    0.     -0.5     1.  

In [67]:
tableau_to_solve = np.array([[2.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 180.0],
                             [1.0, 3.0, 2.0, 0.0, 1.0, 0.0, 0.0, 300.0],
                             [2.0, 1.0, 2.0, 0.0, 0.0, 1.0, 0.0, 240.0],
                             [-8.0, -5.0, -6.0, 0.0, 0.0, 0.0, 1.0, 0.0]])
swapcol_to_solve = np.array([4,5,6,7])

print ("Tableau to Solve\n", tableau_to_solve)
print ("Swap Col to Solve\n", swapcol_to_solve)

var_setting, tableau_out, swapcol_out = simplex(tableau_to_solve, swapcol_to_solve)
p_list = [var_setting[j] * (-1) * tableau_to_solve[-1, j] for j in range(len(var_setting))]
p = sum(p_list)

print ("\nTableau Result\n", tableau_out)
print ("Swap Col Result\n", swapcol_out)
print ("Variable Setting\n", var_setting)
print ("Object Function Value\n", p_list, "sum to", p)
print ("Tableau[-1, -1] =", tableau_out[-1, -1])

Tableau to Solve
 [[   2.    1.    1.    1.    0.    0.    0.  180.]
 [   1.    3.    2.    0.    1.    0.    0.  300.]
 [   2.    1.    2.    0.    0.    1.    0.  240.]
 [  -8.   -5.   -6.    0.    0.    0.    1.    0.]]
Swap Col to Solve
 [4 5 6 7]

Initial Tableau
 [[   2.    1.    1.    1.    0.    0.    0.  180.]
 [   1.    3.    2.    0.    1.    0.    0.  300.]
 [   2.    1.    2.    0.    0.    1.    0.  240.]
 [  -8.   -5.   -6.    0.    0.    0.    1.    0.]]
Initial Swap Column
 [4 5 6 7]

Tableau in progress
 [[   1.     0.5    0.5    0.5    0.     0.     0.    90. ]
 [   0.     2.5    1.5   -0.5    1.     0.     0.   210. ]
 [   0.     0.     1.    -1.     0.     1.     0.    60. ]
 [   0.    -1.    -2.     4.     0.     0.     1.   720. ]]
Swap Col in progressing
 [0 5 6 7]

Tableau in progress
 [[   1.     0.5    0.     1.     0.    -0.5    0.    60. ]
 [   0.     2.5    0.     1.     1.    -1.5    0.   120. ]
 [   0.     0.     1.    -1.     0.     1.     0.    60. ]
 

C:\Users\Youn-Long Lin\Anaconda3\lib\site-packages\ipykernel\__main__.py:20: RuntimeWarning: divide by zero encountered in true_divide
